rsh db@DB01 /home/db/ab72/bin/startdb.sh 
rsh db@DB02 /home/db/ab72/bin/startdb.sh 
rsh db@DB03 /home/db/ab72/bin/startdb.sh 
rsh db@DB04 /home/db/ab72/bin/startdb.sh 
rsh db@DB05 /home/db/ab72/bin/startdb.sh 
rsh db@DB06 /home/db/ab72/bin/startdb.sh 
rsh db@DB07 /home/db/ab72/bin/startdb.sh 
rsh db@DB08 /home/db/ab72/bin/startdb.sh 
rsh db@DB09 /home/db/ab72/bin/startdb.sh 
rsh db@DB10 /home/db/ab72/bin/startdb.sh 
